config/routes.rb
Rails.application.routes.draw do
  get 'words/new'
  get 'users/new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'words#index'
  get "users/about" => "users#about", as: 'users_about'
  get "users/:id/favorite" => "users#favorite", as: 'users_favorite'
  resources :users, only: [:show, :edit, :update]
  get 'words/rank' => 'words#rank', as: 'words_rank'
  get 'words/result' => 'words#result', as: 'words_result'
  resources :words do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :word

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :words, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  validates :word, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_search
    @search = Word.ransack(params[:q])
    @search_words = @search.result
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @word = Word.find(params[:word_id])
    @comment = current_user.comments.new(comment_params)
    @comment.word_id = @word.id
    @comment.save
    redirect_to word_path(@word.id)
  end

  def edit
    @comment = Comment.find_by(word_id: params[:word_id], id: params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id], word_id: params[:word_id])
    @comment.update(comment_params)
    redirect_to word_path(@comment.word.id)
  end

  def destroy
    Comment.find_by(id: params[:id], word_id: params[:word_id]).destroy
    redirect_to word_path(params[:word_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :rate)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_word

  def create
    @favorite = current_user.favorites.new(word_id: @word.id)
    @favorite.save
  end

  def destroy
    @favorite = current_user.favorites.find_by(word_id: @word.id)
    @favorite.destroy
  end

  def set_word
    @word = Word.find(params[:word_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:about]

  def show
    @user = User.find(params[:id])
    @words = @user.words.page(params[:page])
  end

  def favorite
    @user = User.find_by(id: params[:id])
    @favorites = Favorite.where(user_id: @user.id)
    if @user == current_user
      render 'favorite'
    else
      redirect_to words_path
    end
  end
  def about
  
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:tag_name]
      @words = Word.tagged_with("#{params[:tag_name]}").page(params[:page]).order(created_at: :desc)
    else
      @words = Word.all.page(params[:page]).order(created_at: :desc)
    end
  end

  def rank
    @all_ranks = Word.find(Favorite.group(:word_id).order('count(word_id) desc').limit(5).pluck(:word_id))
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @word.user_id = current_user.id
    if @word.save
      redirect_to word_path(@word.id)
    else
      @words = word.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end

  def show
    @word = Word.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @word = Word.find(params[:id])
    if @word.user == current_user
      render 'edit'
    else
      redirect_to word_path(current_user.id)
    end
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to word_path(@word.id)
    else
      render 'edit'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit(:word, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/comments/edit.html.erb
<h1 class="title">コメント編集</h1>
<div class="form">
  <%= form_for @comment,:url => {:action => :update} do |f| %>
    <div class="form-group row" id="star">
      <%= f.label :rate,'評価 ', class: "rate-font" %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>
  <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'comment[rate]',
      half: true,
    });
  </script>  

    <div class=field>
    <%= f.text_area :comment, rows:'5', class: "input" %><br>
    </div>
      <%= f.submit '更新する' %><br>
  <% end %>
</div>
<%= link_to "戻る", word_path(@comment.word) %>

app/views/favorites/_favorite.html.erb
<% if word.favorited_by?(current_user) %>
<%= link_to word_favorites_path(word), method: :delete, remote: true do %>
  <i class="fas fa-bookmark"></i>
<%= word.favorites.count %> ブックマーク
<% end %> 
<% else %>
<%= link_to word_favorites_path(word), method: :post, remote: true do %>
  <i class="far fa-bookmark"></i>
<%= word.favorites.count %> ブックマーク
<% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorites_buttons_'+<%= @favorite.word_id %>).html("<%= j(render partial: 'favorites/favorite', locals: {word: @favorite.word, user: @favorite.user}) %>");

app/views/favorites/destroy.js.erb
$('.favorites_buttons_<%= @word.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {word: @word}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ierukana</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/5b6bab02f4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <nav class="nav">
      <div class= "nav__logo"><%= link_to image_tag('logo.png'), '/', size: "100x100", class: "logo" %></div>
      </div>
        <ul class="nav__list"> 
          <% if user_signed_in? %>
            <li class="nav__list-item">
              <%= link_to '投稿', new_word_path,class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to '新着一覧', words_path,class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to 'ランキング', words_rank_path,class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to 'マイページ', user_path(current_user.id),class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to 'ブックマーク', users_favorite_path(current_user.id),class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class: "link" %>
            </li>
            <li class="search"> 
            <%= search_form_for @search, url: words_result_path  do |f| %>
              <%= f.text_field :word_cont, placeholder: 'キーワードを入力...', class:"search__input" %>
              <%= f.submit ("検索する"), name: nil, class:"button" %>
            <% end %>
          </li>    
          <% else %>
            <li class="nav__list-item">
              <%= link_to '新規登録', new_user_registration_path,class: "link" %>
            </li>
            <li class="nav__list-item">
              <%= link_to 'ログイン', new_user_session_path,class: "link" %>
            </li>
            <li class="nav__list-item">
            <%= link_to 'about', users_about_path,class: "link" %>
          </li>
          <% end %>       
        </ul>
      </nav>
     
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
    </footer>
    </body>
</html>

app/views/users/about.html.erb
<h1 class="title">IERUKANA?へようこそ</h1>

<div class="about">
<h2 class="about__title">IERUKARA?について</h2>
<div class="about__strong">このサイトは「早口言葉投稿サイト」です。</p>
<p class="about__detail">あなただけの早口言葉リスト作ってみませんか？</p>
<p class="about__detail">会員登録することで早口言葉の投稿やお気に入りのリストを管理することが可能です。</p>
<p class="about__detail">タグ検索とフリーワード検索で簡単にサイト内の投稿作品を見つけることが可能です。</p>
<p class="about__detail">評価機能、コメント機能で他のユーザーの投稿作品を評価することが可能です。</p>
<div class="about__strong">このサイトを使って活舌改善しちゃいましょう！！</p>
</div>

app/views/users/edit.html.erb
<h1 class="title">プロフィール編集</h1>
<div class="form">
  <%= form_for(@user) do |f| %>
      <p class="form__label">Name</p>
      <%= f.text_field :name, class: "input" %>
      <%= attachment_image_tag @user, :image, :fill, 60, 60 %>
      <p class="form__label">ProfileImage</p>
      <%= f.attachment_field :image, placeholder: "プロフィール画像", class: "user-edit-form", fallback: "no_image.jpg" %>    
    
      <p class="form__label">Introduction</p>
      <%= f.text_area :introduction, class: "input" %><br>
    
    <div class=actions>
      <%= f.submit 'Update User',class: "btn" %><br>
    </div>
  <% end %>
</div>

app/views/users/favorite.html.erb
<h1 class="title">ブックマーク一覧</h1>
<div class="content">
  <% @favorites.each do |favorite| %>
    <table class="content__table">
      <tr class="content__table-row">
        <td colspan="2" class="content__table-word">
          <%= link_to favorite.word.word , word_path(favorite.word.id),class: "link" %>
        </td>
      <tr>
    </table>
  <% end %>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <h1 class="title">マイページ</h1>
<% else %>
  <h1 class="title">ユーザー情報</h1>
<% end %>

<div class="content">
  <h2 class="content__title">User info</h2>
  <table class="content__table, content__table-box">
      <tr class="content__table-pic"> 
      <td colspan="2">
        <%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "pic" %>
        </td>
      </tr>
      <tr class="content__table-row">
        <th class="content__table-head">name</th>
        <td class="content__table-info"><%= @user.name %></td>
      </tr>
      <tr class="content__table-row">
        <th class="content__table-head">introduction</th>
        <td class="content__table-info"><%= @user.introduction %></td>
      </tr>
      <% if @user == current_user %>
      <tr class="content__table-row"> 
        <td><%= link_to'プロフィール編集',edit_user_path(@user.id),class: "up_btn" %></td>
      </tr>
      <% end %>
  </table>
</div>

<div class="content">
  <h2 class="content__title">投稿作品</h2>
  <% @words.each do |word| %>
    <table class="content__table">
      <tr class="content__table-row">
        <td colspan="2" class="content__table-word"><%= link_to word.word , word_path(word.id),class: "link" %></td>
      </tr>
      <tr class="content__table-row">
        <td class="content__table-tag">タグ：<%= render 'words/tag_list', tag_list: word.tag_list %></td>
      
        <td class="content__table-text right">コメント<%= word.comments.count %>件
          <% if word.user == current_user %>
            <%= link_to'投稿作品編集',edit_word_path(word.id),class: "up_btn"  %>
            <%= link_to '投稿作品削除',word_path(word), method: :delete,data: {confirm:'削除してもよろしいですか？'},class: "d_btn" %>
          <% end %>
        </td>
        </td>
      </tr>
    </table>
  <% end %>
  <%= paginate @words %>
</div>
 

app/views/words/_tag_list.html.erb
<% tag_list.each do |tag| %>
<%= link_to tag, words_path(tag_name: tag), class: "tag" %>
  
<% end %>

app/views/words/_word.html.erb
  <% @words.each do |word| %>
  <table class= "table">
      <tr>
        <td><%= link_to word.word , word_path(word.id) %></td>
      </tr>
      <tr>
        <td><%= render 'words/tag_list', tag_list: word.tag_list,class: "btn-sm btn-info" %></td>
      </tr>
      <tr>
        <td><%= word.user.name %></td>
        <td>コメント<%= word.comments.count %>件</td>
      </tr>
      </table>
  <% end %>

app/views/words/edit.html.erb
<h1 class="title">早口言葉編集</h1>
<div class="form">
  <%= form_for(@word) do |f| %>
    <p class="form__label">早口言葉</p>
    <%= f.text_field :word, class: "input" %>        
    <p class="form__label">タグ</p>
    <%= f.text_field :tag_list, value: @word.tag_list.join(','), class: "col-xs-9" %>
    <div class=actions>
      <%= f.submit 'Update Word',class: "btn" %><br>
    </div>
  <% end %>
</div>

app/views/words/index.html.erb
  <% if params[:tag_name] %>
    <h1 class="title">タグ検索結果一覧</h1>
  <% else %>
    <h1 class="title">新作一覧</h1>
  <% end %>
  
  <div class="content">
    <% @words.each do |word| %>
      <table class= "content__table">
        <tr class="content__table-row">
          <td colspan="3" class="content__table-word">
            <div class="content__table-created_at">
              <%= word.created_at.strftime("%Y-%m-%d %H:%M:%S") %><br>
              <%= link_to word.word , word_path(word.id),class: "link" %><br>
              <div class="content__table-user">
                作者：<%= link_to word.user.name, user_path(word.user.id),class: "link" %>
            </div>
          </td>
        </tr>
        <tr class="content__table-row">
          <td class="content__table-tag">
            タグ：<%= render 'words/tag_list', tag_list: word.tag_list,class: "tag" %>
          </td>
          <td class="content__table-count right" >
            コメント<%= word.comments.count %>件
            <span align="right" class="favorites_buttons_<%= word.id %>">
              <%= render partial: 'favorites/favorite', locals: { word: word} %>
            </span>
          </td>
        </tr>
      </table>
    <% end %>
      <%= paginate @words %>
  </div>

app/views/words/new.html.erb
<h1 class="title">新規投稿</h1>
<div class="form"> 
  <%= form_for(@word) do |f| %>   
        <p class="form__label">早口言葉</p>
        <%= f.text_area :word, class: "input",placeholder: "例：生麦生米生卵" %>
        <p class="form__label">タグ</p>
        <%= f.text_field :tag_list, value: @word.tag_list.join(','), class: "input",placeholder: "単語をコンマで区切ってください。例：基本,有名,ナ行" %><br>
        <%= f.submit 'Create',class: "btn" %>
      <% end %>
</div>

app/views/words/rank.html.erb
<h1 class="title">ブックマークランキング</h1>
<div class="content">
  <% @all_ranks.each.with_index(1) do |rank, i| %>
    <table class= "content__table">
      <tr class="content__table-row">
        <td class="content__table-word">
          第<%= i %>位<br><%= link_to rank.word , word_path(rank.id),class: "link" %>
        <br><div class="content__table-user">ブックマーク数<%= rank.favorites.count %>件    作者：<%= link_to rank.user.name, user_path(rank.user.id),class: "link" %></div></td>
      </tr>
      <tr class="content__table-row">
       <td class="content__table-tag">タグ：<%= render 'words/tag_list', tag_list: rank.tag_list,class: "tag" %> </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/words/result.html.erb
<h1 class="title">検索結果</h1>
<div class="content">
<% @search_words.each do |word| %>
  <table class= "content__table">
    <tr class="content__table-row">
      <td colspan="3" class="content__table-word">
        <%= link_to word.word , word_path(word.id),class: "link" %>
        <br><div class="content__table-user">作者：<%= link_to word.user.name, user_path(word.user.id),class: "link" %></div>
      </td>
    </tr>
    <tr class="content__table-row">
      <td class="content__table-tag"><%= render 'words/tag_list', tag_list: word.tag_list,class: "tag" %></td>
      <td class="right">
        コメント<%= word.comments.count %>件
        <span class="favorites_buttons_<%= word.id %>">
          <%= render partial: 'favorites/favorite', locals: { word: word} %>
        </span>
      </td>
    </tr>
  </table>
  <% end %>
  </div>

app/views/words/show.html.erb
<h1 class="title">作品詳細</h1>
<div class="content">
  <table class="content__table">
    <tr class="content__table-row">
    </tr>
    <tr class="content__table-row">
      <td colspan="2"  class="content__table-word">
        <%= @word.word %>
        <br>
        <div class="content__table-user">
          作者：<%= link_to @word.user.name, user_path(@word.user.id),class: "link" %>
        </div>
      </td>
    </tr>
    <tr class="content__table-row">
      <td class="content__table-tag">
        タグ：<%= render 'words/tag_list', tag_list: @word.tag_list %>
      </td> 
      <td class="right">
        <div class="content__table-fav, favorites_buttons_<%= @word.id %>">
        <%= render partial: 'favorites/favorite', locals: { word: @word} %>
        </div>
      </td>
    </tr>
  </table>
</div>

<div class="comment">
  <h2 class="content__title">コメント一覧</h2>
  <table class="comment__table">
    <% @word.comments.each do |comment| %>  
      <tr class="comment__table-row">  
        <td class="comment__table-pic">
          <%= attachment_image_tag(comment.user, :image, :fill, 70, 70, fallback: "no_image.jpg") %>
          <p class="comment__table-name"><%= link_to comment.user.name, user_path(comment.user.id),class: "user_link" %></p>
        </td>
        <td class="comment__table-rate">
          評価：<%= comment.rate %>点
        </td>
        <td class="comment__table-comment"><%= comment.comment %></td>
        <% if comment.user == current_user %>
          <td class="comment__table-btn">
            <%= link_to 'コメント編集', edit_word_comment_path(comment.word, comment),class: "up_btn" %>
            <%= link_to 'コメント削除', word_comment_path(comment.word, comment), method: :delete,data: {confirm:'削除してもよろしいですか？'},class: "d_btn" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<div class="form">  
  <%= form_for [@word, @comment] do |f| %>
    <div class="form-group row" id="star">
      <%= f.label :rate,'評価 ', class: "rate_font" %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>

    <script>
      $('#star').raty({ 
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'comment[rate]',
        half: true,
      });
    </script>  

    <%= f.text_area :comment, rows:'5', class: "input",placeholder: "コメントをここに" %><br>
    <%= f.submit "送信する", class: "btn" %>
  <% end %>
 </div>